apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  VITE_AUTH_API_URL: "http://acc0cb499559d4840951873c8ac35e68-1539003110.eu-west-3.elb.amazonaws.com/auth"
  VITE_TRANSACTION_API_URL: "http://acc0cb499559d4840951873c8ac35e68-1539003110.eu-west-3.elb.amazonaws.com/api/Operation"
  VITE_LOAN_API_URL: "http://acc0cb499559d4840951873c8ac35e68-1539003110.eu-west-3.elb.amazonaws.com/api/loan-applications"
  VITE_ACCOUNT_API_URL: "http://acc0cb499559d4840951873c8ac35e68-1539003110.eu-west-3.elb.amazonaws.com/accounts"