apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentication-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://adf38ef4bda5a4593988746d5c88f68a-935047858.eu-west-3.elb.amazonaws.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
spec:
  ingressClassName: nginx
  rules:
    - http:  # <-- Pas de champ `host`, toutes les requêtes sont acceptées
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: 8081

          - path: /accounts
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 8083
          - path: /api/Operation
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8084
          - path: /api/loan-applications
            pathType: Prefix
            backend:
              service:
                name: loan-management-service
                port:
                  number: 8087

          - path: /api/prediction
            pathType: Prefix
            backend:
              service:
                name: loan-management-service
                port:
                  number: 8087
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: users-microservice
                port:
                  number: 8082