apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092          # Port standard de Kafka
      targetPort: 9092
  type: ClusterIP         # Service interne au cluster
